server:
  port: 1993
spring:
  application:
    name: lvyou-order
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lvyou?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: root
  rabbitmq:
    addresses: localhost
    username: ipinkhat
    password: ipinkhat
  cloud:
    stream:
      bindings:
        input:
          destination: comment-order
      binders:
        defaultRabbit:
          type: rabbit
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: ly_
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
jwt:
  config:
    ttl: 3600000000
    key: ipinkhat
